#use_frameworks!

platform :ios, '9.0'

target 'PodIJKPlayer_Example' do
  pod 'PodIJKPlayer', :podspec => '../PodIJKPlayer.podspec'

  target 'PodIJKPlayer_Tests' do
    inherit! :search_paths

    
  end
end
